<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Adding All available option under view section</description>
   <name>ActivityOverview-FiltersAndColumns</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>aad4b982-94b5-4257-9ea3-e6f165b04853</testSuiteGuid>
   <testCaseLink>
      <guid>27e6b348-0128-4e2e-93c2-b74c2d48cb54</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NewActivityOverview-LeftNavigation/ActivityOverview-ViewFilterAndColumn</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c71a654-9b6d-457a-b833-3c5a77be9d91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17af37a0-e642-4851-8a23-81279dd09d58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85405a90-248f-4728-bae0-bededbd06ebd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4729b51e-a953-4c49-9fd0-9ae641b3c3c5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
