<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Checking vailable Action on listing in the New Activity Overview</description>
   <name>Activity Overview detail Pop-up Other Section</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>75c768b8-e4f4-4533-85c3-2858a86bba46</testSuiteGuid>
   <testCaseLink>
      <guid>17270349-429b-4361-9758-b4fd166aa4f4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/StepToReUse/ActivityOverview-RedirectionLogin</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28493d03-4f52-450a-b063-66d139f3c61d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b202b25-c9b3-4100-9977-52fbc1db7e61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9fe8645-57d6-47c0-9d7d-6e06d9187e6d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9d0aeccc-dafb-4b65-b92c-1ebfcdad4a1e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/StepToReUse/SearchProducts</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72a6ed9e-3f28-4fa2-b2c1-ce6c9cc342fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>098851d6-44aa-4c12-84ed-87fdd9f54833</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27bbbdba-118f-4237-bc88-7151c71716fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a3b5e1e-2a39-4cee-8cd0-f9d0ff2c198e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>94268562-5fae-4ff8-b0cb-fcc42dc616fe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/StepToReUse/GoToDetailPop-up</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ed27667-d2ce-48ea-b77f-4993112bee96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe06dfef-6943-4d13-84d3-a031481a50a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2905bdc-e376-4ba8-8b7e-042f7fade2ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7f8bad6-c436-4128-8855-3be62054303a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4c1a6467-a974-4df9-b7c0-e47bd31bf191</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/StepToReUse/OtherProductDetails</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0ff81f4-f672-45ac-af15-ecaf027bf3b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dddf17cd-9982-4f34-91a4-909762104c80</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c17b4bf-8a1d-4df8-b1ca-cdc930c81119</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>352a0de9-3963-479b-bb3e-1472044a370f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
