<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>In this case we will check cancel functionality on copied url</description>
   <name>CancelAndRefundMultipleBookings-CopiedURL</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>0517f35f-9d31-4b9d-9440-d61c2b97cf80</testSuiteGuid>
   <testCaseLink>
      <guid>1e3aef09-b438-4f02-96ac-302447f4592c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NewActivityOverview-LeftNavigation/ActivityOverview-CancelBooking-GetOrderIDAndRefund - CopiedURL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d57bcfc-2f1d-4f34-9e0a-118fc7ad10f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5132a933-4f32-4613-84e4-c1c33d30773b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>044ad6e0-0e98-41bf-a7da-22fe9e2be26c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0624d4e-f832-4765-b6fb-03cb04a53256</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
