<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CancelOrder-OnIframeView</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>8330b41a-03a9-4390-8a6f-4072dfa60054</testSuiteGuid>
   <testCaseLink>
      <guid>d18e4ef0-082c-4a54-b09d-7024500ca3d6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NewActivityOverview-LeftNavigation/ActivityOverview-CancelOrder-GetOrderIDAndRefund</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>edb40ad7-f521-4190-92ca-896f985cc014</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2552d74-8760-4db7-a928-ebb69e6a4ee6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c94f7a7-1cd6-42bc-9c19-57239febf27a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f9971eb-44a5-41dc-9b82-3bfbd8deb340</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
