<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Here We can refund on basis of multiple booking exist on page 1</description>
   <name>CancelAndRefundMultipleBookings</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>2fee9bb9-610b-448f-a33d-c7eed7f182a2</testSuiteGuid>
   <testCaseLink>
      <guid>5f72dee3-ea3f-4cca-99d4-8b335f015ff4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NewActivityOverview-LeftNavigation/ActivityOverview-CancelBooking-GetOrderIDAndRefund</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ab158e5-8c3e-4cd6-968f-87f8004596dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd4f8c16-f553-4bd0-88c2-bf92a54f8be5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a858626e-5467-4bad-94f7-f8263f62ebea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8fc788cf-4a33-455b-994e-4c40ec61233c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
