<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Testing of Email Download and Preview Functionality also on the copied url view as well</description>
   <name>EmailDownloadPreview</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>7b03a2f4-671b-4c47-b7a6-02331e85f56d</testSuiteGuid>
   <testCaseLink>
      <guid>e7092e6b-7bae-4f14-9402-c558427a6634</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NewActivityOverview-LeftNavigation/ActivityOverview-EmailDownloadPreview</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55a2bcca-a784-4cc6-a867-b4c9fc1ee501</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a27e701-8c3a-445f-8ed8-cd283c9bf1e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27878809-f020-4bf4-b069-bd8e16f1e1b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad675cb4-2623-4ec2-b7bb-5e3bee5d48dd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d2f61350-69d1-4372-96d5-d3d6764db1d2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NewActivityOverview-LeftNavigation/ActivityOverview-EmailDownloadPreview-CopiedURL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a81cae0-e3b8-41a7-a0d6-66f48187d138</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6cf75ae5-c377-44f0-8cc4-2f4493630288</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6dabc6da-d1fd-42e7-8717-6b6ff74f9027</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78a0f05a-733e-46e9-a3e9-4b179a4c99bc</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
