<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>checking all pagination and count of records by adding lenght of each tr in data table</description>
   <name>Pagination</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>662b5361-c50a-4faa-a2ec-a57cfcf671a1</testSuiteGuid>
   <testCaseLink>
      <guid>4dae7db0-e3d9-4b4c-ae39-edcfb566b29a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NewActivityOverview-LeftNavigation/ActivityOverview-Pagination</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b25450b-a5ee-4941-bebc-1592d743ce87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d806c7d5-a274-4624-87ff-87ad4a7fca92</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e4a9cd5-0977-4dd5-8b37-506aae86b994</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>321aede3-32d8-4e1b-8f60-7a37169b1f42</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
